# -*- coding: utf-8 -*-
"""LogisticRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oa1s1EaBShs_cbtRP3Y2worUY4Gljq5G
"""

# Commented out IPython magic to ensure Python compatibility.
 import pandas as pd
from matplotlib import pyplot as plt
# %matplotlib inline

df= pd.read_csv("/content/sample_data/insurance_data.csv")
df.head()

plt.scatter(df.age,df.bought_insurance,marker='+',color='red')

from sklearn.model_selection import train_test_split

X_train, x_test, y_train, y_test = train_test_split(df[['age']],df.bought_insurance,train_size=0.8)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

x_test

y_predicted=model.predict(x_test)
y_predicted

model.predict_proba(x_test)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_predicted)

model.score(x_test,y_test)

